/** Declaration file generated by dts-gen */

export = react_model_presenter;

declare function react_model_presenter(Model: any, ...args: any[]): any;

declare namespace react_model_presenter {
    const prototype: {
    };

}

